      - name: Show workspace structure
        run: Get-ChildItem -Recurse

      - name: Compile Inno Setup Script
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          scriptPath: setup.iss

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Spinyard Installer
          path: ./Installer/SpinyardSetup.exe