# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: .NET Core Desktop with Inno Setup Installer

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: InventoryManagementSystem.sln
      Project_Path: Inventory.Presentation.Wpf/Inventory.Presentation.Wpf.csproj
      # Define an absolute path for the publish directory
      PUBLISH_DIR: ${{ github.workspace }}/publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Build and publish the application
        # This step now publishes to the absolute path defined above
        run: dotnet publish ${{ env.Project_Path }} --configuration Release --runtime win-x64 --output ${{ env.PUBLISH_DIR }}

      - name: Setup Inno Setup
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2

      - name: Compile the Inno Setup script
        # This now passes the absolute path directly to Inno Setup
        run: iscc setup.iss "/dSourcePath=${{ env.PUBLISH_DIR }}"

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Spinyard Installer
          path: ./Installer/SpinyardSetup.exe
